import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const hero = readFileSync(resolve(root, 'assets/hero-schierke.webp')).toString('base64')
const favicon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <rect width="64" height="64" rx="14" fill="#131a16"/>
  <circle cx="32" cy="33" r="21" fill="none" stroke="#b8d4b2" stroke-width="2"/>
  <path d="M15 40h34M21 38l9-20 16 20M27 28h15" fill="none" stroke="#866fa2" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>
  <circle cx="32" cy="33" r="3" fill="#d8e9ce"/>
</svg>`

const source = `// Generated by scripts/embed-art.mjs from assets/hero-schierke.webp.\n` +
  `export const SKIN_ART = 'data:image/webp;base64,${hero}'\n` +
  `export const SKIN_FAVICON = \`data:image/svg+xml,\${encodeURIComponent(${JSON.stringify(favicon)})}\`\n`

writeFileSync(resolve(root, 'shared/art.js'), source)
console.log(`Embedded ${hero.length} base64 characters into shared/art.js`)
